name: Scrape Kicktipp → Publish JSON

on:
  schedule:
    # every 5 minutes Fri-Sun, 2pm-10pm Berlin time (12pm-8pm UTC)
    - cron: "*/5 12-20 * * 5"  # Friday
    - cron: "*/5 12-20 * * 6"  # Saturday
    - cron: "*/5 12-20 * * 0"  # Sunday
    # Special: Jan 13-15, 2026 (Tue-Thu), 5pm-10pm Berlin time (3pm-8pm UTC)
    - cron: "*/5 15-20 13-15 1 2"  # Jan 13-15, 2026
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: scrape-kicktipp
  cancel-in-progress: true

jobs:
  build-json:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -U pip
          pip install -r scraper/requirements.txt

      - name: Run scraper + standings
        run: |
          cd scraper
          python scrape_kicktipp.py
          python compute_wurstliga.py

      # Publish only the "data" folder as a static site
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./data

  deploy:
    needs: build-json
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4